In [11]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [12]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

**Import library**

In [13]:
from google_play_scraper import app

In [14]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [15]:
from google_play_scraper import reviews, Sort

result, continuation_token = reviews(
    'jp.naver.line.android',
    lang= 'id',
    country= 'id',
    sort= Sort.NEWEST,
    count= 10000,
    filter_score_with=None
)

Show data yang sudah di crawling

In [16]:
import pandas as pd
df_busu = pd.DataFrame(result)
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,abb05e65-661a-417d-98fe-68ec01d8f0d2,irfan faturachman,https://play-lh.googleusercontent.com/a-/ALV-U...,"Ux nya sangat buruk, harusnya lebih fokus ke c...",1,663,14.7.2,2024-06-02 07:34:13,None,None,14.7.2
9996,e807d7bb-b97e-4489-99c6-a479a326960c,jasdar. Almayser,https://play-lh.googleusercontent.com/a-/ALV-U...,Aplikasi paling tidak bermanfaat,1,0,14.7.2,2024-06-02 03:52:12,None,None,14.7.2
9997,1d21bc73-6cf7-4f10-9e11-9a62f021ae82,Suwa Sini,https://play-lh.googleusercontent.com/a-/ALV-U...,Minta data yg hp lm vudio nya kluarin dong,5,0,14.7.2,2024-06-02 01:55:02,None,None,14.7.2
9998,fcd236d4-2e71-47b7-a458-ff5f28c5c972,INSOMNIAT CHANNEL,https://play-lh.googleusercontent.com/a-/ALV-U...,jelek gak bisa akses kontak,1,0,None,2024-06-02 01:37:04,None,None,None
9999,63ae32e0-572f-46a5-87a3-afcc242f30d4,Muhamad Hirman,https://play-lh.googleusercontent.com/a-/ALV-U...,Aplikasi keren,5,0,14.7.2,2024-06-01 21:03:59,None,None,14.7.2

Ambil data yang dibutuhkan

In [17]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,irfan faturachman,1,2024-06-02 07:34:13,"Ux nya sangat buruk, harusnya lebih fokus ke c..."
9996,jasdar. Almayser,1,2024-06-02 03:52:12,Aplikasi paling tidak bermanfaat
9997,Suwa Sini,5,2024-06-02 01:55:02,Minta data yg hp lm vudio nya kluarin dong
9998,INSOMNIAT CHANNEL,1,2024-06-02 01:37:04,jelek gak bisa akses kontak
9999,Muhamad Hirman,5,2024-06-01 21:03:59,Aplikasi keren

In [18]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [19]:
#Simpan dataset kedalam file
my_df.to_csv("DataSetLine.csv", index = False)